service: ostersundsrevyn-server
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: revydev
  region: eu-north-1
  iam:
    role: arn:aws:iam::851725656891:role/revyRole
  deploymentMethod: direct

plugins:
  - serverless-webpack

package: 
  individually: true

functions:
  getMembers:
    handler: functions/getTeam/index.handler
    events:
      - httpApi:
          path: /team
          method: GET


resources:
  Resources:
    TeamTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Team
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
